// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_List = require("rescript/lib/js/belt_List.js");
var ReadlineSync = require("./ReadlineSync.bs.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

var NotToken = /* @__PURE__ */Caml_exceptions.create("Part2.Token.NotToken");

var Operator = {};

var Token = {
  NotToken: NotToken,
  Operator: Operator
};

var WrongExpression = /* @__PURE__ */Caml_exceptions.create("Part2.Interpreter.WrongExpression");

function make(text) {
  return {
          text: text,
          pos: 0,
          currentToken: /* Eof */0
        };
}

function getNextSingleToken(interpreter) {
  if (interpreter.pos > (interpreter.text.length - 1 | 0)) {
    interpreter.pos = interpreter.pos + 1 | 0;
    return /* Eof */0;
  }
  var $$char = interpreter.text.charAt(interpreter.pos);
  switch ($$char) {
    case " " :
        interpreter.pos = interpreter.pos + 1 | 0;
        return /* Whitespace */1;
    case "+" :
        interpreter.pos = interpreter.pos + 1 | 0;
        return {
                TAG: /* Operator */1,
                _0: /* Plus */0
              };
    case "-" :
        interpreter.pos = interpreter.pos + 1 | 0;
        return {
                TAG: /* Operator */1,
                _0: /* Subtract */1
              };
    case "0" :
    case "1" :
    case "2" :
    case "3" :
    case "4" :
    case "5" :
    case "6" :
    case "7" :
    case "8" :
    case "9" :
        break;
    default:
      throw {
            RE_EXN_ID: NotToken,
            Error: new Error()
          };
  }
  interpreter.pos = interpreter.pos + 1 | 0;
  return {
          TAG: /* Integer */0,
          _0: Belt_Int.fromString($$char)
        };
}

function getNextToken(interpreter) {
  var _left;
  while(true) {
    var left = _left;
    var right = getNextSingleToken(interpreter);
    if (left !== undefined) {
      if (typeof left === "number") {
        if (left === /* Eof */0) {
          return /* Eof */0;
        }
        
      } else if (left.TAG === /* Integer */0 && typeof right !== "number" && right.TAG === /* Integer */0) {
        _left = {
          TAG: /* Integer */0,
          _0: Math.imul(left._0, 10) + right._0 | 0
        };
        continue ;
      }
      interpreter.pos = interpreter.pos - 1 | 0;
      return left;
    }
    if (right === 0) {
      return /* Eof */0;
    }
    _left = right;
    continue ;
  };
}

function extractTokens(interpreter) {
  var extractTokens_ = function (interpreter, _list) {
    while(true) {
      var list = _list;
      var token = getNextToken(interpreter);
      if (typeof token === "number") {
        if (token === 0) {
          return Belt_List.add(list, token);
        }
        continue ;
      }
      var list$1 = Belt_List.add(list, token);
      _list = list$1;
      continue ;
    };
  };
  return Belt_List.reverse(extractTokens_(interpreter, /* [] */0));
}

function expr(interpreter) {
  var tokens = Belt_List.keep(extractTokens(interpreter), (function (token) {
          if (typeof token === "number") {
            return token === 0;
          } else {
            return true;
          }
        }));
  var left = Belt_List.get(tokens, 0);
  var operator = Belt_List.get(tokens, 1);
  var right = Belt_List.get(tokens, 2);
  var end = Belt_List.get(tokens, 3);
  if (left !== undefined) {
    if (typeof left === "number") {
      throw {
            RE_EXN_ID: WrongExpression,
            Error: new Error()
          };
    }
    if (left.TAG === /* Integer */0) {
      if (operator !== undefined) {
        if (typeof operator === "number") {
          throw {
                RE_EXN_ID: WrongExpression,
                Error: new Error()
              };
        }
        if (operator.TAG === /* Operator */1) {
          if (right !== undefined) {
            if (typeof right === "number") {
              throw {
                    RE_EXN_ID: WrongExpression,
                    Error: new Error()
                  };
            }
            if (right.TAG === /* Integer */0) {
              if (end !== undefined) {
                if (end === 0) {
                  var right$1 = right._0;
                  var left$1 = left._0;
                  if (operator._0) {
                    return left$1 - right$1 | 0;
                  } else {
                    return left$1 + right$1 | 0;
                  }
                }
                throw {
                      RE_EXN_ID: WrongExpression,
                      Error: new Error()
                    };
              }
              throw {
                    RE_EXN_ID: WrongExpression,
                    Error: new Error()
                  };
            }
            throw {
                  RE_EXN_ID: WrongExpression,
                  Error: new Error()
                };
          } else {
            throw {
                  RE_EXN_ID: WrongExpression,
                  Error: new Error()
                };
          }
        } else {
          throw {
                RE_EXN_ID: WrongExpression,
                Error: new Error()
              };
        }
      } else {
        throw {
              RE_EXN_ID: WrongExpression,
              Error: new Error()
            };
      }
    } else {
      throw {
            RE_EXN_ID: WrongExpression,
            Error: new Error()
          };
    }
  } else {
    throw {
          RE_EXN_ID: WrongExpression,
          Error: new Error()
        };
  }
}

var Interpreter = {
  WrongExpression: WrongExpression,
  make: make,
  getNextSingleToken: getNextSingleToken,
  getNextToken: getNextToken,
  extractTokens: extractTokens,
  expr: expr
};

function main(param) {
  while(true) {
    try {
      var text = ReadlineSync.question("calc>");
      var interpreter = make(text);
      var value = expr(interpreter);
      console.log(value);
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      console.log("error: ", exn);
    }
  };
  
}

main(undefined);

exports.Token = Token;
exports.Interpreter = Interpreter;
exports.main = main;
/*  Not a pure module */
