// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReadlineSync = require("readline-sync");

function question(preStr) {
  return ReadlineSync.question(preStr);
}

exports.question = question;
/* readline-sync Not a pure module */
